### ISSUE TITLE
Clean up images on extension page

### ISSUE THREAD

**Issue by yavorg** [auth0-extensions/auth0-deploy-cli-extension#12]
The images and formatting needs to be cleaned up:
* The text and images are too close together making it hard to read
* The top screenshot has some faded text at the top 
* Improve the image resolution, clean up identifiable info 

![image](https://user-images.githubusercontent.com/1086030/48234432-7003b900-e36e-11e8-8a40-e2a3458f3878.png)

**Comment by fyockm** [comment]
@yavorg spacing of the images was fixed with 6c133c2486c1433fb79f61b7f0fcbc2b115b6ffd, but the images themselves have not been changed yet.

@zxan1285 could you create new screenshots and submit a PR to address?

**Comment by yavorg** [comment]
@fyockm @zxan1285 we should also fix the images in the README of this repo :)
