### ISSUE TITLE
The extension is untrusted

### ISSUE THREAD

**Issue by DavidePastore** [auth0-extensions/auth0-deploy-cli-extension#16]
When I follow the installation steps, the summary shows me a message saying that "this is an untrusted extension that has not been reviewed by Auth0".

<img width="258" alt="untrusted extension" src="https://user-images.githubusercontent.com/1949364/51596634-c0180380-1ef9-11e9-85da-6148f76ead19.PNG">

**Comment by fyockm** [comment]
@DavidePastore that message is displayed any time you install any extension via the "+ Create Extension" button. You can safely ignore the warning in this case.
