### ISSUE TITLE
Insufficient scopes when creating the application via Github installation

### ISSUE THREAD

**Issue by nfadili** [auth0-extensions/auth0-deploy-cli-extension#18]
### Issue
Following the installation instructions laid out [here](https://auth0.com/docs/extensions/deploy-cli/guides/install-deploy-cli) the scopes that are requested are not sufficient for running the a0deploy cli to export from a tenant. The export fails because it requires `read:roles`.

### To recreate:
1. Follow the instructions to create the extension via the 'Create Extension' button (it will automatically create an application with scopes assigned)
2. Install the a0deploy cli locally
3. Plug in the client id and client secret from the application that the extension created
4. Run `a0deploy export -c config.json --strip -f directory -o dir/path`

The error I get is
```
Problem loading tenant data from Auth0 APIError: {"statusCode":403,"error":"Forbidden","message":"Insufficient scope, expected any of: read:roles","errorCode":"insufficient_scope"}
```

### To resolve
I was able to resolve this by creating the application manually as described [here](https://github.com/auth0/auth0-deploy-cli#to-create-client-application-by-hand) and adding all the scopes the extension creates by default as well as the `read:roles` scope. Using this application I am able to export my tenant configuration :+1: I suggest updating the scopes that the extension applies to the application that it creates. Though, I am not sure what in my tenant is causing it to require `read:roles` in the first place...

**Comment by fyockm** [comment]
Fixed by #19
