### ISSUE TITLE
created Client Application is "generic" - can't see permissions

### ISSUE THREAD

**Issue by dgobaud** [auth0-extensions/auth0-deploy-cli-extension#20]
1. The created Client application is of type "generic" - what is that and where is it documented?

2. Because the Client is "generic" I can't seemingly see/modify the Management API permissions the application has. The Github deploy app has same "generic" type and problem.

3. Generic type does not seem to be an option for creating via Dashboard.

![image](https://user-images.githubusercontent.com/240811/59889259-6e788580-9380-11e9-87a4-9d84dac73d67.png)

**Comment by ShayMe21** [comment]
> 1. The created Client application is of type "generic" - what is that and where is it documented?

Generic Applications are like system clients, they're only used by Auth0 extensions and tools. The reasoning behind this is, so someone does not mistakenly change client grants for the Application authorized to Management APIv2. Changes to this Application's client grants can definitely break the extension/tools.

> 2. Because the Client is "generic" I can't seemingly see/modify the Management API permissions the application has. The Github deploy app has same "generic" type and problem.

You can modify the scopes/client grants using Management APIv2 only. However, remember that the motivation behind making the application generic type was so it does not show under the APIs's Machine to machine applications and to avoid people from modifying the client grants which can break the extensions/tool.

> 3. Generic type does not seem to be an option for creating via Dashboard.

Answered above.

**Comment by dgobaud** [comment]
I don't know I'm skeptical it is a good idea to use undocumented things. It should at least be documented and explained. And probably made public so other developers who have same concerns can use them. Using undocumented features probably means 1) they should be documented and made public or 2) you should stop using them

**Comment by dgobaud** [comment]
yes
