### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by ecbrodie** [auth0-extensions/auth0-deploy-cli-extension#25]
Can you please add a changelog to this project?

It is not very comforting when a new version becomes available for this extension, but there are no easy ways to know about what changed, especially for folks less familiar with git and GitHub.

**Comment by trosborn** [comment]
This customer originally contacted us via support. I submitted internal feedback about this but also I suggested he leave this issue open as I'm not sure if this is better handled here or via the product team.

**Comment by ecbrodie** [comment]
This is not a case of the issue going stale. Rather, it is Auth0's negligence and unwillingness to maintain proper maintenance of its open source software. How is an Auth0 customer supposed to install extension updates without having a reliable way to understand what has changed? The common answer in the open soruce world: **A Changelog!**

@trosborn you and Auth0 are the blocker, not me. Please see that a Changelog for this project is created.

**Comment by trosborn** [comment]
Hi @ecbrodie. I understand it is frustrating that there is no changelog for this, but we are a startup and not everything is documented. Additionally, I don't think many, if any, important changes happen to this project. It is just a way to run a terminal in the browser which contains the deploy CLI, and that project does have a changelog: https://github.com/auth0/auth0-deploy-cli/blob/master/CHANGELOG.md

 This is why if you navigate to the Deploy CLI extension in your dashboard and you click the documentation button, you actually get pointed to the Deploy CLI repo, not the Deploy CLI extension repo. Ultimately, upgrading the Deploy CLI extension should be no different than making an upgrade to your terminal.

**Comment by ecbrodie** [comment]
@trosborn Auth0 is a company with [over 500 employees](https://ca.linkedin.com/company/auth0) and [multiple](https://auth0.com/blog/auth0-announces-record-year/) [years](https://auth0.com/blog/auth0-closes-year-of-impressive-growth-in-2018/) [of](https://auth0.com/blog/auth0-closes-most-impactful-year-yet/) rapidly revenue growth. I'd say this is well past the point of "startup".

Although I understand that there is a high coupling between the auth0-deploy-cli-extension project and the auth0-deploy-cli project, they are still ultimately separate projects that have different deployment cycles and don't even have matching versions. That is enough to warrant a separate changelog.

I would never upgrade anything in my terminal without understanding what the changes consisted of first. So, why would I blindly press an upgrade button without understanding what the consequences are for that? Not just for myself, but for my employer and it's large customer base?

I perceive that our ideologies around the stewardship of open source software is too wide of a gap to cover. Therefore I'm simply going to close this issue out because I predict that unfortunately Auth0 is going to chose not to do anything about this.
