### ISSUE TITLE
Auth0 "Create Extension" does not accept repo

### ISSUE THREAD

**Issue by noah-empire** [auth0-extensions/auth0-deploy-cli-extension#6]
Tried this out on several tenants and was always met with the same response. 

<img width="676" alt="screen shot 2018-05-11 at 1 21 17 pm" src="https://user-images.githubusercontent.com/30630888/39937596-3cb07360-551e-11e8-9f0a-f2a262101cb0.png">

Putting an invalid URL in changes the error to "The URL is invalid"

**Comment by fyockm** [comment]
@noah-empire I just tried and it *is* working for me. Please re-open the issue if you're still unable to install.

**Comment by janslow** [comment]
@fyockm, I'm also getting this issue (on both an EU and an AU tenant).

Also, if I try to install the [`webtask.json`](https://raw.githubusercontent.com/auth0-extensions/auth0-deploy-cli-extension/master/webtask.json) directly, I get an error saying `webtask.json` is missing the `codeUrl` property.

![image](https://user-images.githubusercontent.com/1253367/48772968-f351d280-ecbd-11e8-9be4-2c34c4f7bc66.png)

(I'm happy to create a new issue if you'd prefer)
