### ISSUE TITLE
Unable to uninstall auth0 deploy cli extension

### ISSUE THREAD

**Issue by emirklj-virgil** [auth0-extensions/auth0-deploy-cli-extension#8]
When I click uninstall extension I get the message:
IMPORTANT: You are about to delete 'Auth0 Deploy CLI'. This means that it will not be available anymore. Do you really want to uninstall this extension? Doing so will also remove the rule and the token endpoint.. Do you want to continue?

But when I click OK nothing happens

**Comment by fyockm** [comment]
@emirklj-virgil thanks for reporting! this should now be fixed from the extension gallery.
